// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    '[id]': typeof import('./pages/hi/[id].vue')['default']
    404: typeof import('./pages/404.vue')['default']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    App: typeof import('./app.vue')['default']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    'Component.vue2': typeof import('./node_modules/@nuxtjs/color-mode/dist/runtime/component.vue2.vue')['default']
    'Component.vue3': typeof import('./node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    Default: typeof import('./layouts/default.vue')['default']
    Error404: typeof import('./node_modules/@nuxt/ui-templates/dist/templates/error-404.vue')['default']
    Error500: typeof import('./node_modules/@nuxt/ui-templates/dist/templates/error-500.vue')['default']
    ErrorDev: typeof import('./node_modules/@nuxt/ui-templates/dist/templates/error-dev.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Home: typeof import('./layouts/home.vue')['default']
    InputEntry: typeof import('./components/InputEntry.vue')['default']
    Loading: typeof import('./node_modules/@nuxt/ui-templates/dist/templates/loading.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    NuxtErrorPage: typeof import('./node_modules/nuxt/dist/app/components/nuxt-error-page.vue')['default']
    NuxtRoot: typeof import('./node_modules/nuxt/dist/app/components/nuxt-root.vue')['default']
    Pages: typeof import('./pages/index.vue')['default']
    PageView: typeof import('./components/PageView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Undefined: typeof import('./pages/index.vue')['default']
    UnoIcon: typeof import('./node_modules/@unocss/nuxt/runtime/UnoIcon.vue')['default']
    Welcome: typeof import('./node_modules/@nuxt/ui-templates/dist/templates/welcome.vue')['default']
  }
}

export {}
