// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    Alpha: typeof import('./components/color-picker/alpha.vue')['default']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    Checkerboard: typeof import('./components/checkerboard.vue')['default']
    Container: typeof import('./components/container.vue')['default']
    FixedWidgets: typeof import('./components/fixed-widgets.vue')['default']
    Hue: typeof import('./components/color-picker/hue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Saturation: typeof import('./components/color-picker/saturation.vue')['default']
    VueCodemirror: typeof import('./components/vue-codemirror.vue')['default']
  }
}

export {}
